# This file was modified to bypass GitHub download infrastructure errors
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-level: 18

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VARIUSONLINE_976F8 }}
        run: firebase deploy --only hosting --project variusonline-976f8
